# Generated by Django 4.2 on 2023-05-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstocourse',
            name='assignment',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userstocourse',
            name='courseID',
            field=models.IntegerField(),
        ),
    ]
