# Generated by Django 4.2 on 2023-05-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_alter_userstocourse_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fName',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lName',
            field=models.CharField(default=False, max_length=30, null=True),
        ),
    ]
